idle_bg = "#333333"
idle_fg = "#dddddd"
info_bg = "#333333"
info_fg = "#ffd680"
good_bg = "#58cc5c"
good_fg = "#000000"
warning_bg = "#eeaa00"
warning_fg = "#000000"
critical_bg = "#ff3333"
critical_fg = "#000000"
#separator = "\ue0b2"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
