sensors:
  - hwmon: /sys/class/hwmon
    name: coretemp
    indices: [1]
fans:
  - tpacpi: /proc/acpi/ibm/fan
levels:
  - [ 0, 0 , 53 ]
  - [ 1, 48, 60 ]
  - [ 2, 51, 61 ]
  - [ 3, 53, 63 ]
  - [ 4, 56, 65 ]
  - [ 5, 59, 66 ]
  - [ 7, 63, 255]
