#!/bin/bash
SESS_NAME=$HOSTNAME"-2x2"
if [ -z "$TMUX" ]; then
  tmux has-session -t $SESS_NAME > /dev/null 2>&1
  if [ $? != 0 ]; then
    cd $HOME
    tmux new-session -s $SESS_NAME -d
    tmux splitw \; splitw \; splitw \; selectl tiled \; selectp -t 0 \; attach
  fi
  tmux attach -t $SESS_NAME
fi
