#start-at-login = false
start-at-login = true
accordion-padding = 0
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#after-startup-command = [ 'exec-and-forget $HOME/.nix-profile/bin/clipcatd -r' ]
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]
# inner.horizontal = 11
# inner.vertical = 11
# outer.left = 11
# outer.bottom = 11
# outer.top = 11
# outer.right = 11
### for borders width = 12 ###
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 6
outer.right = 6

[mode.main.binding]
alt-y = 'exec-and-forget open -n /Applications/Alacritty.app'
#cmd-alt-p = 'exec-and-forget $HOME/dev/tool/IN_PATH/clipcat-menu'
#cmd-alt-y = 'exec-and-forget $HOME/.nix-profile/bin/flameshot gui'
alt-d = 'exec-and-forget cat <(ls $HOME/Applications/ /Applications/ /Applications/Utilities/ /System/Applications/ /System/Applications/Utilities/ /System/Library/CoreServices/ | grep "\.app$") <(ls $HOME/dev/tool/go_path/bin | rg worklog-helper | xargs -I {} readlink -f "$HOME/dev/tool/go_path/bin/{}") | choose -s 36 -c CE5C00 | xargs -I {} open -a "{}"'


alt-w = 'close'
alt-m = 'move-mouse monitor-lazy-center'

alt-h = 'focus --boundaries all-monitors-outer-frame --ignore-floating left'
alt-j = 'focus --boundaries all-monitors-outer-frame --ignore-floating down'
alt-k = 'focus --boundaries all-monitors-outer-frame --ignore-floating up'
alt-l = 'focus --boundaries all-monitors-outer-frame --ignore-floating right'

alt-p = 'focus --ignore-floating up'
alt-n = 'focus --ignore-floating down'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-space = 'fullscreen'
alt-shift-space = 'layout floating tiling'

alt-t = ['flatten-workspace-tree', 'layout v_accordion']
alt-b = ['flatten-workspace-tree', 'layout v_accordion']
alt-e = ['flatten-workspace-tree', 'layout tiles horizontal vertical']

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'

alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'

alt-comma = 'mode service'
alt-r = 'mode resize'

cmd-h = []
cmd-alt-h = []

[mode.resize.binding]
h = 'resize width -100'
j = 'resize height +100'
k = 'resize height -100'
l = 'resize width +100'
enter = 'mode main'
esc = 'mode main'

[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main']
enter = ['reload-config', 'mode main']
esc = ['reload-config', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
1 = 1
2 = 2
3 = 3
