start-at-login = true
accordion-padding = 0
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
after-startup-command = [ 'exec-and-forget $HOME/.nix-profile/bin/clipcatd -r' ]

[gaps]
inner.horizontal = 5
inner.vertical   = 5
outer.left       = 5
outer.bottom     = 5
outer.top        = 5
outer.right      = 5

[mode.main.binding]
alt-y = 'exec-and-forget open -n /Applications/Alacritty.app'
alt-b = 'exec-and-forget open -n /Applications/Firefox.app'
cmd-alt-p = 'exec-and-forget $HOME/.nix-profile/bin/clipcat-menu'
cmd-alt-y = 'exec-and-forget $HOME/.nix-profile/bin/flameshot gui'
alt-d = 'exec-and-forget cat <(ls /Applications/ /Applications/Utilities/ /System/Applications/ /System/Applications/Utilities/ | grep "\.app$") <(ls $HOME/dev/tool/go_path/bin | xargs -I {} readlink -f "$HOME/dev/tool/go_path/bin/{}") | choose -s 36 -c CE5C00 | xargs -I {} open -a "{}"'

alt-w = 'close'

alt-h = 'focus --boundaries all-monitors-outer-frame left'
alt-j = 'focus --boundaries all-monitors-outer-frame down'
alt-k = 'focus --boundaries all-monitors-outer-frame up'
alt-l = 'focus --boundaries all-monitors-outer-frame right'

alt-p = 'focus left'
alt-n = 'focus right'

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

alt-space = 'fullscreen'
alt-shift-space = 'layout floating tiling'

alt-t = 'layout h_accordion'
alt-e = 'layout tiles horizontal vertical'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
alt-shift-4 = 'move-node-to-workspace --focus-follows-window 4'

cmd-h = []
cmd-alt-h = []

alt-shift-r = 'flatten-workspace-tree'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = 'built-in'
2 = 'DELL'
3 = 'VA'
