[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555753"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#9add44"
magenta = "#ad7fa8"
red = "#ff3939"
white = "#eeeeec"
yellow = "#fce94f"

[colors.cursor]
cursor = "#dddddd"
text = "#000000"

[colors.normal]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#4eba06"
magenta = "#75507b"
red = "#e12121"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.primary]
background = "#333333"
foreground = "#dddddd"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 18

[font.bold]
family = "Iosevka SS04"
style = "Bold"

[font.bold_italic]
family = "Iosevka SS04"
style = "Bold Italic"

[font.italic]
family = "Iosevka SS04"
style = "Italic"

[font.normal]
family = "Iosevka SS04"
style = "Regular"

[scrolling]
history = 99999

[selection]
semantic_escape_chars = ",│`|\"' ()[]{}<>\t"

[window]
decorations = "None"
